name: Create Plugin.jar

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        artifactPath="$(pwd)/target"
        echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
        echo "artifactName=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV
        echo git_hash=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_ENV
        mvn clean package
        mv "${artifactPath}/target/$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout).jar" "$(pwd)/target/$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)-$(git rev-parse --short "$GITHUB_SHA").jar"
        
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifactName }}-${{ env.git_hash }}.jar
        path: ${{ env.artifactPath }}/${{ env.artifactName }}-${{ env.git_hash }}.jar
